### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by cneira** [galdolber/clojure-objc#13]
Is this available for simple console objc apps on Freebsd ?, or clojure-objc is only meant to run on macs ?

**Comment by galdolber** [comment]
I haven't tried, but it should work.
Look into https://github.com/galdolber/lein-objcbuild, if should be easy to adapt to compile for any arch and do not depend on xcode.

**Comment by galdolber** [comment]
I added support for building standalone apps. It breaks all the dependencies with XCode.
Here's an example project github.com/galdolber/cljobjc
I only tested it on macos, let me know if it works on FreeBSD.

**Comment by galdolber** [comment]
I've been trying to compile on linux. It's still not working, for this to work I need to get CoreFoundation, there're a couple of open source implementations that should compile on linux. With that in place you still need to compile j2objc and clojure-objc on linux.

**Comment by cneira** [comment]
Thanks !

**Comment by galdolber** [comment]
Sorry about the misunderstanding, this is not working yet, I'm leaving it out for now.
The hard part here is to get j2objc working on top of gnustep. I've been trying to port it, but its harder than i thought. Once j2objc fully compiles, getting clojure-objc to work on any *nix environment should be really easy.
